with:
  host: ${{ secrets.HOST }}
  username: ${{ secrets.USERNAME }}
  port: ${{ secrets.PORT }}
  key: ${{ secrets.SSH_PRIVATE_KEY }}
  timeout: 60s
  command_timeout: 20m

  script: |
    set -e

    cd /var/www/Platinum-real-estate

    git pull origin main
    npm install
    npm run build
    pm2 restart platinum-realtors
    pm2 save